import 'package:flutter/material.dart';

import '../models.dart';

class MockData {
  static final List<CategoryItem> categories = [
    CategoryItem(id: 'electronics', name: 'Electronics', icon: Icons.electrical_services_rounded, imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80'),
    CategoryItem(id: 'mobiles', name: 'Mobiles', icon: Icons.phone_android_rounded, imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80'),
    CategoryItem(id: 'laptops', name: 'Laptops', icon: Icons.laptop_mac_rounded, imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80'),
    CategoryItem(id: 'computers', name: 'Computers', icon: Icons.desktop_windows_rounded, imageUrl: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?auto=format&fit=crop&w=900&q=80'),
    CategoryItem(id: 'fashion', name: 'Fashion', icon: Icons.checkroom_rounded, imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80'),
    CategoryItem(id: 'men-fashion', name: "Men's Fashion", icon: Icons.man_rounded, imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80'),
    CategoryItem(id: 'women-fashion', name: "Women's Fashion", icon: Icons.female_rounded, imageUrl: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80'),
    CategoryItem(id: 'shoes', name: 'Shoes', icon: Icons.shopping_bag_rounded, imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80'),
    CategoryItem(id: 'watches', name: 'Watches', icon: Icons.watch_rounded, imageUrl: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=900&q=80'),
    CategoryItem(id: 'home-kitchen', name: 'Home & Kitchen', icon: Icons.kitchen_rounded, imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80'),
    CategoryItem(id: 'furniture', name: 'Furniture', icon: Icons.chair_alt_rounded, imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80'),
    CategoryItem(id: 'grocery', name: 'Grocery', icon: Icons.local_grocery_store_rounded, imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=80'),
    CategoryItem(id: 'beauty', name: 'Beauty', icon: Icons.face_rounded, imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80'),
    CategoryItem(id: 'sports', name: 'Sports', icon: Icons.sports_soccer_rounded, imageUrl: 'https://images.unsplash.com/photo-1541534401786-2077eed87a74?auto=format&fit=crop&w=900&q=80'),
    CategoryItem(id: 'books', name: 'Books', icon: Icons.menu_book_rounded, imageUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=900&q=80'),
    CategoryItem(id: 'toys', name: 'Toys', icon: Icons.toys_rounded, imageUrl: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?auto=format&fit=crop&w=900&q=80'),
    CategoryItem(id: 'accessories', name: 'Accessories', icon: Icons.watch_rounded, imageUrl: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=900&q=80'),
    CategoryItem(id: 'automotive', name: 'Automotive', icon: Icons.directions_car_rounded, imageUrl: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=80'),
    CategoryItem(id: 'appliances', name: 'Appliances', icon: Icons.kitchen_rounded, imageUrl: 'https://images.unsplash.com/photo-1585518419759-7fe2e0fbf8a6?auto=format&fit=crop&w=900&q=80'),
  ];

  static final List<PromoBanner> banners = [
    PromoBanner(
      title: 'Fresh Savings',
      subtitle: 'Up to 70% off on curated essentials',
      imageUrl: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80',
      color: const Color(0xFFF59E0B),
    ),
    PromoBanner(
      title: 'New Season Drop',
      subtitle: 'Style meets comfort in every purchase',
      imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80',
      color: const Color(0xFF14B8A6),
    ),
    PromoBanner(
      title: 'Smart Tech Deals',
      subtitle: 'Explore premium devices & accessories',
      imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
      color: const Color(0xFF2563EB),
    ),
  ];

  static final List<Product> products = [
    Product(
      id: 'P1001',
      name: 'Aero Pro Laptop 14',
      category: 'Laptops',
      brand: 'Aero',
      imageUrls: [
        'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80',
      ],
      price: 89999,
      discountPrice: 67999,
      discountPercentage: 24,
      rating: 4.8,
      reviewCount: 216,
      stock: 44,
      description: 'Premium ultrabook design with crisp display, fast SSD, AI-powered performance, and lightweight portability for work and entertainment.',
      specifications: ['14-inch 2.8K display', 'Intel i7 12th Gen', '16GB RAM', '1TB SSD', 'Backlit keyboard'],
      colors: ['Silver', 'Black', 'Blue'],
      sizes: ['13-inch', '14-inch', '15-inch'],
      seller: Seller(name: 'Aero Tech', location: 'Bengaluru', rating: 4.9, positiveReviews: 98),
      deliveryInfo: 'Free delivery by 2-4 days',
      returnPolicy: '7-day easy return policy',
      warrantyInfo: '1-year official brand warranty',
      isFeatured: true,
      isNewArrival: true,
    ),
    Product(
      id: 'P1002',
      name: 'Nebula X Smartphone',
      category: 'Mobiles',
      brand: 'Nebula',
      imageUrls: [
        'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=900&q=80',
      ],
      price: 64999,
      discountPrice: 49999,
      discountPercentage: 23,
      rating: 4.7,
      reviewCount: 430,
      stock: 112,
      description: 'A flagship phone with vibrant OLED screen, ultra-fast camera and long-lasting battery for media lovers and creators.',
      specifications: ['6.7-inch OLED', '256GB storage', '48MP triple camera', '5000mAh battery', '5G enabled'],
      colors: ['Midnight Black', 'Silver', 'Ocean Blue'],
      sizes: ['128GB', '256GB', '512GB'],
      seller: Seller(name: 'Nebula Store', location: 'Delhi', rating: 4.8, positiveReviews: 95),
      deliveryInfo: 'Free delivery and same-day dispatch on selected pin codes',
      returnPolicy: 'No questions asked replacement within 7 days',
      warrantyInfo: '2-year warranty on mobile device',
      isFeatured: true,
    ),
    Product(
      id: 'P1003',
      name: 'Harbor Smart Watch',
      category: 'Watches',
      brand: 'Harbor',
      imageUrls: [
        'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=900&q=80',
      ],
      price: 21999,
      discountPrice: 14999,
      discountPercentage: 32,
      rating: 4.6,
      reviewCount: 189,
      stock: 120,
      description: 'Elegant smartwatch with wellness tracking, multi-sport modes, GPS, and a premium metal finish.',
      specifications: ['AMOLED display', '7-day battery', 'Heart rate sensor', 'Water resistant', 'Bluetooth calling'],
      colors: ['Graphite', 'Rose Gold', 'Black'],
      sizes: ['40mm', '42mm', '46mm'],
      seller: Seller(name: 'Harbor Essentials', location: 'Hyderabad', rating: 4.7, positiveReviews: 94),
      deliveryInfo: 'Free delivery in 3 days',
      returnPolicy: '10-day replacement and refund',
      warrantyInfo: '1-year manufacturer warranty',
      isFeatured: true,
    ),
    Product(
      id: 'P1004',
      name: 'Vanta Air Speaker',
      category: 'Electronics',
      brand: 'Vanta',
      imageUrls: [
        'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1518444065439-e933c06ce9cd?auto=format&fit=crop&w=900&q=80',
      ],
      price: 17999,
      discountPrice: 11999,
      discountPercentage: 33,
      rating: 4.5,
      reviewCount: 136,
      stock: 90,
      description: 'Portable smart speaker with deep bass, voice assistant and room-filling sound for home entertainment.',
      specifications: ['360° sound', 'Bluetooth 5.3', '12-hour battery', 'IPX5 water-resistant', 'Dual driver'],
      colors: ['Black', 'Cream', 'Blue'],
      sizes: ['Standard'],
      seller: Seller(name: 'Vanta Audio', location: 'Pune', rating: 4.6, positiveReviews: 91),
      deliveryInfo: 'Free delivery and EMI available',
      returnPolicy: '7-day return, no questions asked',
      warrantyInfo: '1-year service support',
    ),
    Product(
      id: 'P1005',
      name: 'UrbanBlend Office Chair',
      category: 'Furniture',
      brand: 'UrbanBlend',
      imageUrls: [
        'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80',
      ],
      price: 24999,
      discountPrice: 17999,
      discountPercentage: 28,
      rating: 4.3,
      reviewCount: 84,
      stock: 52,
      description: 'Ergonomic chair with lumbar support, breathable mesh, and a premium office-grade build.',
      specifications: ['Mesh back', 'Adjustable tilt', 'Gas lift', '360° swivel', 'High-density foam'],
      colors: ['Black', 'Grey', 'White'],
      sizes: ['Standard'],
      seller: Seller(name: 'UrbanBlend Living', location: 'Chennai', rating: 4.7, positiveReviews: 93),
      deliveryInfo: 'White-glove delivery available',
      returnPolicy: '14-day return policy',
      warrantyInfo: '18 months warranty',
      isNewArrival: true,
    ),
    Product(
      id: 'P1006',
      name: 'Luma Skin Care Kit',
      category: 'Beauty',
      brand: 'Luma',
      imageUrls: [
        'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=900&q=80',
      ],
      price: 4999,
      discountPrice: 3299,
      discountPercentage: 34,
      rating: 4.4,
      reviewCount: 210,
      stock: 180,
      description: 'Dermatologist recommended skincare bundle for hydration, glow and skin barrier protection.',
      specifications: ['Cleanser', 'Vitamin C serum', 'Moisturizer', 'Sunscreen'],
      colors: ['Rose', 'Pearl', 'Gold'],
      sizes: ['Travel', 'Standard'],
      seller: Seller(name: 'Luma Beauty', location: 'Mumbai', rating: 4.8, positiveReviews: 96),
      deliveryInfo: 'Free shipping for orders over ₹499',
      returnPolicy: 'Easy replacements on unopened products',
      warrantyInfo: 'No warranty required',
      isFeatured: true,
    ),
    Product(
      id: 'P1007',
      name: 'Northstar Running Shoes',
      category: 'Shoes',
      brand: 'Northstar',
      imageUrls: [
        'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=900&q=80',
      ],
      price: 6999,
      discountPrice: 4799,
      discountPercentage: 31,
      rating: 4.6,
      reviewCount: 410,
      stock: 82,
      description: 'Performance footwear built with lightweight cushioning, support and grip for daily runs.',
      specifications: ['Breathable mesh', 'Dual-density foam', 'Grip outsole', 'Supportive fit'],
      colors: ['Black', 'Orange', 'White'],
      sizes: ['6', '7', '8', '9', '10'],
      seller: Seller(name: 'Northstar Footwear', location: 'Jaipur', rating: 4.7, positiveReviews: 94),
      deliveryInfo: 'Same-day dispatch if ordered before 12 PM',
      returnPolicy: '30-day exchange policy',
      warrantyInfo: '6-month quality guarantee',
      isNewArrival: true,
    ),
    Product(
      id: 'P1008',
      name: 'Zenith Gaming Desk',
      category: 'Computers',
      brand: 'Zenith',
      imageUrls: [
        'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80',
      ],
      price: 34999,
      discountPrice: 27999,
      discountPercentage: 20,
      rating: 4.5,
      reviewCount: 67,
      stock: 39,
      description: 'A premium workstation desk with cable management, spacious top layer and strong build quality.',
      specifications: ['Large tabletop', 'Reinforced frame', 'Cable routing', 'Height adjustable'],
      colors: ['Walnut', 'Black'],
      sizes: ['Standard'],
      seller: Seller(name: 'Zenith Workspace', location: 'Ahmedabad', rating: 4.8, positiveReviews: 92),
      deliveryInfo: 'Delivery in 4-5 business days',
      returnPolicy: '14-day replacement policy',
      warrantyInfo: '12 months furniture warranty',
    ),
  ];

  static final List<Review> sampleReviews = [
    Review(userName: 'Aarav', rating: 5, comment: 'The quality is excellent and the delivery was fast. Very happy with the purchase.', date: '3 days ago'),
    Review(userName: 'Riya', rating: 4, comment: 'Looks premium and works exactly as expected. Good value for money.', date: '1 week ago'),
    Review(userName: 'Karan', rating: 5, comment: 'Packaging was great and product matched the description perfectly.', date: '2 weeks ago'),
  ];

  static final List<PaymentMethod> paymentMethods = [
    PaymentMethod(name: 'UPI', icon: Icons.account_balance_wallet_rounded),
    PaymentMethod(name: 'Card', icon: Icons.credit_card_rounded),
    PaymentMethod(name: 'Net Banking', icon: Icons.account_balance_rounded),
    PaymentMethod(name: 'Cash on Delivery', icon: Icons.local_shipping_rounded),
  ];

  static final List<Coupon> coupons = [
    Coupon(code: 'WELCOME10', description: '10% off on first purchase', discountAmount: 10),
    Coupon(code: 'SAVE200', description: '₹200 instant discount', discountAmount: 200),
    Coupon(code: 'FLASH30', description: '30% off on electronics', discountAmount: 30),
  ];

  static final List<Address> addresses = [
    Address(id: 'A1', type: 'Home', line1: '14, Green Acres Residency', city: 'Bengaluru', state: 'Karnataka', zip: '560103', phone: '9876543210'),
    Address(id: 'A2', type: 'Office', line1: '17th Floor, Skyline Tower', city: 'Mumbai', state: 'Maharashtra', zip: '400001', phone: '9123456780'),
  ];

  static final UserProfile userProfile = UserProfile(
    name: 'Riya Sharma',
    email: 'riya.sharma@example.com',
    mobile: '9876543210',
    city: 'Bengaluru',
  );

  static final List<Order> orders = [
    Order(
      id: 'ORD-8734',
      status: 'Out for Delivery',
      date: '12 Sep 2026',
      total: 49999,
      items: [CartItem(product: products[1], quantity: 1)],
    ),
    Order(
      id: 'ORD-7620',
      status: 'Delivered',
      date: '24 Aug 2026',
      total: 17999,
      items: [CartItem(product: products[2], quantity: 1)],
    ),
  ];
}
